DELETE FROM TBDesconto
DELETE FROM TBLocacao
DELETE FROM TBClienteCNPJ
DELETE FROM TBClienteCPF
DELETE FROM TBFuncionario
DELETE FROM TBParceiros
DELETE FROM TBTaxasDaLocacao
DELETE FROM TBTipoVeiculo
DELETE FROM TBVeiculos
DELETE FROM TBTaxasServicos
DBCC CHECKIDENT ( TBDesconto, RESEED,0 )
DBCC CHECKIDENT ( TBLocacao, RESEED,0 )
DBCC CHECKIDENT ( TBClienteCNPJ, RESEED,0 )
DBCC CHECKIDENT ( TBClienteCPF, RESEED,0 )
DBCC CHECKIDENT ( TBFuncionario, RESEED,0 )
DBCC CHECKIDENT ( TBParceiros, RESEED,0 )
DBCC CHECKIDENT ( TBTaxasDaLocacao, RESEED,0 )
DBCC CHECKIDENT ( TBTipoVeiculo, RESEED,0 )
DBCC CHECKIDENT ( TBVeiculos, RESEED,0 )
DBCC CHECKIDENT ( TBTaxasServicos, RESEED,0 )