DELETE FROM TBDescontos
DELETE FROM TBLocacao
DELETE FROM TBClientesCNPJ
DELETE FROM TBClientesCPF
DELETE FROM TBClientesBase
DELETE FROM TBFuncionarios
DELETE FROM TBParceiros
DELETE FROM TBTaxasDaLocacao
DELETE FROM TBTiposVeiculo
DELETE FROM TBVeiculos
DELETE FROM TBTaxasServicos
DBCC CHECKIDENT ( TBDescontos, RESEED,0 )
DBCC CHECKIDENT ( TBLocacao, RESEED,0 )
DBCC CHECKIDENT ( TBClientesCNPJ, RESEED,0 )
DBCC CHECKIDENT ( TBClientesCPF, RESEED,0 )
DBCC CHECKIDENT ( TBClientesBase, RESEED,0 )
DBCC CHECKIDENT ( TBFuncionarios, RESEED,0 )
DBCC CHECKIDENT ( TBParceiros, RESEED,0 )
DBCC CHECKIDENT ( TBTaxasDaLocacao, RESEED,0 )
DBCC CHECKIDENT ( TBTiposVeiculo, RESEED,0 )
DBCC CHECKIDENT ( TBVeiculos, RESEED,0 )
DBCC CHECKIDENT ( TBTaxasServicos, RESEED,0 )